import { Character } from '../../types';
import { DEFAULT_STATS } from '../../statsSystem';

// Marai minion-tier enemies
export const MARAI_MINIONS: Character[] = [
  {
    id: 'marai_tidecaller',
    name: 'Marai Tidecaller',
    role: 'enemy',
    class: 'mage',
    region: 'marai_territory',
    tier: 'minion',
    faction: 'marai',
    hp: 50,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 50,
      attackDamage: 7,
      abilityPower: 12,
      speed: 0.7,
    },
    inventory: [
      { itemId: 'mana_crystal', quantity: 1 },
    ],
  },
  {
    id: 'marai_warrior',
    name: 'Marai Warrior',
    role: 'enemy',
    class: 'juggernaut',
    region: 'marai_territory',
    tier: 'minion',
    faction: 'marai',
    hp: 65,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 65,
      attackDamage: 9,
      armor: 4,
      speed: 0.65,
    },
    inventory: [
      { itemId: 'longsword', quantity: 1 },
    ],
  },
  {
    id: 'marai_scout',
    name: 'Marai Scout',
    role: 'enemy',
    class: 'marksman',
    region: 'marai_territory',
    tier: 'minion',
    faction: 'marai',
    hp: 45,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 45,
      attackDamage: 11,
      movementSpeed: 140,
      speed: 0.8,
    },
  },
];

// Marai elite-tier enemies
export const MARAI_ELITES: Character[] = [
  {
    id: 'marai_wave_bearer',
    name: 'Marai Wave Bearer',
    role: 'enemy',
    class: 'mage',
    region: 'marai_territory',
    tier: 'elite',
    faction: 'marai',
    hp: 120,
    abilities: [],
    level: 3,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 120,
      attackDamage: 10,
      abilityPower: 18,
      armor: 3,
      magicResist: 5,
      speed: 0.75,
    },
    inventory: [
      { itemId: 'mana_crystal', quantity: 2 },
      { itemId: 'negatron_cloak', quantity: 1 },
    ],
  },
  {
    id: 'marai_deep_guardian',
    name: 'Marai Deep Guardian',
    role: 'enemy',
    class: 'juggernaut',
    region: 'marai_territory',
    tier: 'elite',
    faction: 'marai',
    hp: 150,
    abilities: [],
    level: 3,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 150,
      attackDamage: 12,
      armor: 10,
      magicResist: 6,
      speed: 0.6,
    },
    inventory: [
      { itemId: 'cloth_armor', quantity: 2 },
      { itemId: 'longsword', quantity: 1 },
    ],
  },
];

// Marai boss-tier enemies
export const MARAI_BOSSES: Character[] = [
  {
    id: 'marai_siren_warden',
    name: 'Marai Siren Warden',
    role: 'enemy',
    class: 'mage',
    region: 'marai_territory',
    tier: 'boss',
    faction: 'marai',
    hp: 250,
    abilities: [],
    level: 5,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 250,
      attackDamage: 15,
      abilityPower: 25,
      armor: 5,
      magicResist: 8,
      speed: 0.7,
    },
    inventory: [
      { itemId: 'mana_crystal', quantity: 3 },
      { itemId: 'void_staff', quantity: 1 },
    ],
  },
  {
    id: 'marai_leviathan',
    name: 'Marai Leviathan',
    role: 'enemy',
    class: 'juggernaut',
    region: 'marai_territory',
    tier: 'boss',
    faction: 'marai',
    hp: 300,
    abilities: [],
    level: 5,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 300,
      attackDamage: 18,
      armor: 15,
      magicResist: 10,
      speed: 0.65,
    },
    inventory: [
      { itemId: 'thornmail', quantity: 1 },
      { itemId: 'warmogs_armor', quantity: 1 },
    ],
  },
];
