import { RegionEvent } from '../../eventSystem';

export const MARAI_EVENTS: RegionEvent[] = [
  {
    id: 'marai_event_coral_treasure',
    name: 'Coral Treasure Cache',
    description: 'Ancient coral structures conceal valuable treasures',
    flavor: 'Bioluminescent crystals illuminate hidden riches',
    type: 'treasure',
    region: 'marai_territory',
    rewardType: 'items',
    itemRewards: ['mana_crystal', 'mana_crystal', 'negatron_cloak'],
    successText: 'You collect the shimmering treasures of the deep.',
  },
  {
    id: 'marai_event_siren_blessing',
    name: 'Siren\'s Blessing',
    description: 'The sirens recognize your strength and offer aid',
    flavor: 'Ethereal voices echo through the water',
    type: 'relic',
    region: 'marai_territory',
    rewardType: 'buff',
    statModifiers: {
      abilityPower: 15,
      magicResist: 8,
    },
    successText: 'You are blessed with the sirens\' power.',
  },
  {
    id: 'marai_event_deep_guardian_trial',
    name: 'Deep Guardian\'s Trial',
    description: 'An ancient guardian tests your worth',
    flavor: 'A colossal creature emerges from the abyss',
    type: 'encounter',
    region: 'marai_territory',
    enemyId: 'marai_deep_guardian',
    rewardType: 'mixed',
    goldReward: 300,
    itemRewards: ['thornmail', 'warmogs_armor'],
    successText: 'The guardian bows, recognizing you as worthy.',
    failureText: 'The guardian spares you, impressed by your effort.',
  },
  {
    id: 'marai_event_leviathan_whisper',
    name: 'Leviathan\'s Whisper',
    description: 'The ancient Leviathan imparts forbidden knowledge',
    flavor: 'Telepathic thoughts flood your mind with power',
    type: 'mystery',
    region: 'marai_territory',
    rewardType: 'buff',
    statModifiers: {
      health: 75,
      abilityPower: 20,
    },
    successText: 'You absorb the Leviathan\'s ancient wisdom.',
  },
  {
    id: 'marai_event_pearl_of_wisdom',
    name: 'Pearl of Wisdom',
    description: 'A luminous pearl contains knowledge of the ages',
    flavor: 'The pearl gleams with inner light',
    type: 'treasure',
    region: 'marai_territory',
    rewardType: 'items',
    itemRewards: ['void_staff', 'mana_crystal'],
    goldReward: 200,
    successText: 'You claim the legendary pearl.',
  },
  {
    id: 'marai_event_cursed_shell',
    name: 'Cursed Shell Armor',
    description: 'Beautiful armor made from a cursed shell',
    flavor: 'The surface writhes with dark energy',
    type: 'mystery',
    region: 'marai_territory',
    rewardType: 'curse',
    successText: 'You harness the shell\'s power without succumbing to the curse.',
    failureText: 'The curse weakens you, but you keep the armor anyway.',
  },
];
