import { RegionEvent } from '../../eventSystem';

export const DEMACIA_EVENTS: RegionEvent[] = [
  {
    id: 'demacia_event_petricite_discovery',
    name: 'Petricite Crystal Discovery',
    description: 'You discover a glowing petricite crystal',
    flavor: 'The magical stone pulses with arcane energy...',
    type: 'treasure',
    region: 'demacia',
    rewardType: 'items',
    itemRewards: ['mana_crystal', 'mana_crystal'],
    successText: 'You carefully extract the shimmering crystals and pocket them.',
  },
  {
    id: 'demacia_event_royal_emissary',
    name: 'Royal Emissary',
    description: 'A messenger from Demacia offers you a reward for your service',
    flavor: 'A dignified official approaches with gratitude in their eyes',
    type: 'quest',
    region: 'demacia',
    rewardType: 'gold',
    goldReward: 250,
    successText: 'The emissary grants you a generous reward for protecting Demacia.',
  },
  {
    id: 'demacia_event_garen_duel',
    name: 'Garen\'s Challenge',
    description: 'Garen himself appears and offers an honorable duel',
    flavor: 'The legendary warrior extends his hand in challenge',
    type: 'encounter',
    region: 'demacia',
    enemyId: 'garen',
    rewardType: 'mixed',
    goldReward: 500,
    itemRewards: ['warmogs_armor'],
    successText: 'Garen nods in respect, acknowledging your strength.',
    failureText: 'Garen bests you, but shows mercy and allows you to recover.',
  },
  {
    id: 'demacia_event_artifact_vault',
    name: 'Ancient Vault Uncovered',
    description: 'An old vault containing ancient Demacian artifacts',
    flavor: 'Dust and magic swirl as the vault opens',
    type: 'treasure',
    region: 'demacia',
    rewardType: 'items',
    itemRewards: ['void_staff', 'longsword', 'cloth_armor'],
    successText: 'You claim the legendary artifacts within.',
  },
  {
    id: 'demacia_event_blessed_boon',
    name: 'Divine Boon',
    description: 'A blessed relic grants you temporary power',
    flavor: 'Golden light surrounds you with warmth',
    type: 'relic',
    region: 'demacia',
    rewardType: 'buff',
    statModifiers: {
      health: 50,
      armor: 10,
    },
    successText: 'You feel empowered by the divine blessing.',
  },
  {
    id: 'demacia_event_cursed_armor',
    name: 'Cursed Plate Armor',
    description: 'Suspicious armor lies on the ground, gleaming with dark energy',
    flavor: 'The metallic surface seems to pulse with malevolent intent',
    type: 'mystery',
    region: 'demacia',
    rewardType: 'curse',
    successText: 'You resist the curse and gain the armor\'s benefits.',
    failureText: 'The curse takes hold! You gain the armor but suffer a penalty.',
  },
];
