import { Character } from '../../types';
import { DEFAULT_STATS } from '../../statsSystem';

// Ice Sea minion-tier enemies
export const ICE_SEA_MINIONS: Character[] = [
  {
    id: 'ice_sea_frostborn',
    name: 'Frostborn Warrior',
    role: 'enemy',
    class: 'juggernaut',
    region: 'ice_sea',
    tier: 'minion',
    faction: 'frostborn',
    hp: 60,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 60,
      attackDamage: 8,
      armor: 6,
      magicResist: 3,
      attackSpeed: 0.6,
    },
    inventory: [
      { itemId: 'longsword', quantity: 1 },
      { itemId: 'cloth_armor', quantity: 1 },
    ],
  },
  {
    id: 'ice_sea_glacial_mage',
    name: 'Glacial Mage',
    role: 'enemy',
    class: 'mage',
    region: 'ice_sea',
    tier: 'minion',
    faction: 'frostborn',
    hp: 48,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 48,
      attackDamage: 6,
      abilityPower: 11,
      magicResist: 4,
      attackSpeed: 0.7,
    },
  },
  {
    id: 'ice_sea_frost_archer',
    name: 'Frost Archer',
    role: 'enemy',
    class: 'marksman',
    region: 'ice_sea',
    tier: 'minion',
    faction: 'frostborn',
    hp: 50,
    abilities: [],
    level: 1,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 50,
      attackDamage: 10,
      movementSpeed: 135,
      magicResist: 2,
      attackSpeed: 0.75,
    },
  },
];

// Ice Sea elite-tier enemies
export const ICE_SEA_ELITES: Character[] = [
  {
    id: 'ice_sea_blizzard_knight',
    name: 'Blizzard Knight',
    role: 'enemy',
    class: 'juggernaut',
    region: 'ice_sea',
    tier: 'elite',
    faction: 'frostborn',
    hp: 140,
    abilities: [],
    level: 3,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 140,
      attackDamage: 13,
      armor: 12,
      magicResist: 7,
      attackSpeed: 0.6,
    },
    inventory: [
      { itemId: 'cloth_armor', quantity: 2 },
      { itemId: 'longsword', quantity: 1 },
    ],
  },
  {
    id: 'ice_sea_frost_sorcerer',
    name: 'Frost Sorcerer',
    role: 'enemy',
    class: 'mage',
    region: 'ice_sea',
    tier: 'elite',
    faction: 'frostborn',
    hp: 110,
    abilities: [],
    level: 3,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 110,
      attackDamage: 9,
      abilityPower: 20,
      armor: 2,
      magicResist: 8,
      attackSpeed: 0.7,
    },
    inventory: [
      { itemId: 'mana_crystal', quantity: 2 },
      { itemId: 'negatron_cloak', quantity: 1 },
    ],
  },
];

// Ice Sea boss-tier enemies
export const ICE_SEA_BOSSES: Character[] = [
  {
    id: 'ice_sea_frost_tyrant',
    name: 'Frost Tyrant',
    role: 'enemy',
    class: 'juggernaut',
    region: 'ice_sea',
    tier: 'boss',
    faction: 'frostborn',
    hp: 320,
    abilities: [],
    level: 5,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 320,
      attackDamage: 19,
      armor: 18,
      magicResist: 12,
      attackSpeed: 0.65,
    },
    inventory: [
      { itemId: 'thornmail', quantity: 1 },
      { itemId: 'warmogs_armor', quantity: 1 },
    ],
  },
  {
    id: 'ice_sea_eternal_winter',
    name: 'Eternal Winter Spirit',
    role: 'enemy',
    class: 'mage',
    region: 'ice_sea',
    tier: 'boss',
    faction: 'frostborn',
    hp: 260,
    abilities: [],
    level: 5,
    experience: 0,
    stats: {
      ...DEFAULT_STATS,
      health: 260,
      attackDamage: 12,
      abilityPower: 28,
      armor: 6,
      magicResist: 15,
      attackSpeed: 0.7,
    },
    inventory: [
      { itemId: 'mana_crystal', quantity: 3 },
      { itemId: 'void_staff', quantity: 1 },
    ],
  },
];
