import { GameEvent } from '../../events/eventTypes';

export const ICE_SEA_EVENTS: GameEvent[] = [
  {
    id: 'ice_sea_frozen_vault',
    title: 'Frozen Treasure Vault',
    description: 'Ice-locked vault containing powerful artifacts',
    type: 'treasure',
    icon: '❄️',
    rarity: 'rare',
    originRegions: ['ice_sea'],
    data: {
      treasureType: 'cache',
      items: ['longsword', 'cloth_armor', 'negatron_cloak'],
      gold: 350,
      risk: 'none',
    },
  },
  {
    id: 'ice_sea_winter_blessing',
    title: 'Eternal Winter\'s Blessing',
    description: 'The spirit of winter grants you its protection',
    type: 'dialogue',
    icon: '❄️',
    rarity: 'epic',
    originRegions: ['ice_sea'],
    data: {
      npcName: 'Winter Spirit',
      dialogue: 'The spirit of winter acknowledges your strength and grants you protection.',
    },
  },
  {
    id: 'ice_sea_frost_champion',
    title: 'Frostborn Champion\'s Trial',
    description: 'A legendary Frostborn warrior challenges you',
    type: 'encounter',
    icon: '⛸️',
    rarity: 'epic',
    originRegions: ['ice_sea'],
    data: {
      enemyName: 'Frostborn Champion',
      enemyLevel: 10,
      goldReward: 400,
      experienceReward: 200,
    },
  },
  {
    id: 'ice_sea_glacial_artifacts',
    title: 'Glacial Artifacts Discovery',
    description: 'Ancient artifacts frozen in pristine ice',
    type: 'treasure',
    icon: '🏺',
    rarity: 'rare',
    originRegions: ['ice_sea'],
    data: {
      treasureType: 'cache',
      items: ['void_staff', 'thornmail'],
      gold: 300,
      risk: 'none',
    },
  },
  {
    id: 'ice_sea_blizzard_spirits',
    title: 'Blizzard Spirits\' Gift',
    description: 'The spirits of the blizzard offer you power',
    type: 'dialogue',
    icon: '🌪️',
    rarity: 'epic',
    originRegions: ['ice_sea'],
    data: {
      npcName: 'Blizzard Spirits',
      dialogue: 'Howling winds carry whispers as the spirits grant you their savage power.',
    },
  },
];
