import { RegionEvent } from '../../eventSystem';

export const ICE_SEA_EVENTS: RegionEvent[] = [
  {
    id: 'ice_sea_event_frozen_treasure',
    name: 'Frozen Treasure Vault',
    description: 'Ice-locked vault containing powerful artifacts',
    flavor: 'Crystalline ice sparkles with magical energy',
    type: 'treasure',
    region: 'ice_sea',
    rewardType: 'items',
    itemRewards: ['longsword', 'cloth_armor', 'negatron_cloak'],
    successText: 'You melt the ice and claim the frozen treasures.',
  },
  {
    id: 'ice_sea_event_eternal_winter_blessing',
    name: 'Eternal Winter\'s Blessing',
    description: 'The spirit of winter grants you its protection',
    flavor: 'Snowflakes swirl in an ethereal dance around you',
    type: 'relic',
    region: 'ice_sea',
    rewardType: 'buff',
    statModifiers: {
      armor: 20,
      magicResist: 15,
    },
    successText: 'Winter\'s blessing empowers your defenses.',
  },
  {
    id: 'ice_sea_event_frostborn_champion',
    name: 'Frostborn Champion\'s Trial',
    description: 'A legendary Frostborn warrior challenges you',
    flavor: 'An imposing figure of ice and power stands before you',
    type: 'encounter',
    region: 'ice_sea',
    enemyId: 'ice_sea_frost_tyrant',
    rewardType: 'mixed',
    goldReward: 400,
    itemRewards: ['warmogs_armor', 'thornmail', 'void_staff'],
    successText: 'The champion acknowledges your mastery of combat.',
    failureText: 'The champion spares you, seeing potential in your spirit.',
  },
  {
    id: 'ice_sea_event_glacial_artifacts',
    name: 'Glacial Artifacts Discovery',
    description: 'Ancient artifacts frozen in pristine ice',
    flavor: 'The ice glows with age-old magic',
    type: 'treasure',
    region: 'ice_sea',
    rewardType: 'items',
    itemRewards: ['void_staff', 'thornmail'],
    goldReward: 350,
    successText: 'You carefully extract the ancient ice artifacts.',
  },
  {
    id: 'ice_sea_event_blizzard_spirits',
    name: 'Blizzard Spirits\' Gift',
    description: 'The spirits of the blizzard offer you power',
    flavor: 'Howling winds carry whispers of ancient magic',
    type: 'relic',
    region: 'ice_sea',
    rewardType: 'buff',
    statModifiers: {
      attackDamage: 12,
      attackSpeed: 0.15,
    },
    successText: 'You are infused with the blizzard\'s savage power.',
  },
  {
    id: 'ice_sea_event_cursed_frostbite',
    name: 'Cursed Frostbite Weapon',
    description: 'A weapon wreathed in cursed frost energy',
    flavor: 'Cold radiates from the blade in unnatural ways',
    type: 'mystery',
    region: 'ice_sea',
    rewardType: 'curse',
    successText: 'You master the cursed frostbite.',
    failureText: 'The curse freezes your limbs momentarily.',
  },
];
