import { NOXUS_MINIONS, NOXUS_ELITES, NOXUS_BOSSES } from './enemies';

export const NOXUS_QUEST_PATHS = [
  {
    id: 'noxus_path_1',
    name: 'The Crimson March',
    flavor: 'March through Noxian military territory',
    paths: [
      {
        id: 'noxus_path_1_safe',
        name: 'Safe Route - Training Grounds',
        description: 'Face Noxian recruits and trainees',
        difficulty: 'safe' as const,
        enemyIds: [
          NOXUS_MINIONS[0].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[0].id, NOXUS_MINIONS[4].id,
          NOXUS_ELITES[0].id,
          NOXUS_MINIONS[0].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[4].id, NOXUS_MINIONS[0].id,
          NOXUS_BOSSES[0].id,
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
      },
      {
        id: 'noxus_path_1_balanced',
        name: 'Balanced Route - Legion Outpost',
        description: 'Challenge stationed legionnaires',
        difficulty: 'safe' as const,
        enemyIds: [
          'random:minion:legion', 'random:minion:legion', 'random:minion:warband', 'random:minion:legion',
          'random:elite:legion',
          'random:minion:legion', 'random:minion:warband', 'random:minion:legion', 'random:minion:legion',
          'random:boss:legion',
        ],
        lootType: 'mixed' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
        finalBossId: 'noxus_war_general',
      },
      {
        id: 'noxus_path_1_risky',
        name: 'Risky Route - Fortress Assault',
        description: 'Storm a Noxian fortress',
        difficulty: 'risky' as const,
        enemyIds: [
          'random:minion:legion', 'random:minion:legion', 'random:minion:legion', 'random:minion:legion',
          'random:elite:legion',
          'random:minion:legion', 'random:minion:legion', 'random:minion:legion', 'random:minion:legion',
          'darius',
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.2,
        rewardExpMultiplier: 1.2,
        finalBossId: 'darius',
      },
    ],
  },
  {
    id: 'noxus_path_2',
    name: 'Blood and Steel',
    flavor: 'Face Noxus\' deadliest warriors',
    paths: [
      {
        id: 'noxus_path_2_safe',
        name: 'Safe Route - Warband Camps',
        description: 'Encounter roaming warbands',
        difficulty: 'safe' as const,
        enemyIds: [
          NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id,
          NOXUS_ELITES[0].id,
          NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id, NOXUS_MINIONS[1].id,
          NOXUS_BOSSES[1].id,
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
      },
      {
        id: 'noxus_path_2_balanced',
        name: 'Balanced Route - Battle Arena',
        description: 'Fight in the combat pits',
        difficulty: 'safe' as const,
        enemyIds: [
          'random:minion:warband', 'random:minion:legion', 'random:minion:warband', 'random:minion:legion',
          'random:elite:warband',
          'random:minion:warband', 'random:minion:legion', 'random:minion:warband', 'random:minion:legion',
          'random:boss:warband',
        ],
        lootType: 'mixed' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
        finalBossId: 'noxus_warlord',
      },
      {
        id: 'noxus_path_2_risky',
        name: 'Risky Route - Champion\'s Trial',
        description: 'Face Darius, the Hand of Noxus',
        difficulty: 'risky' as const,
        enemyIds: [
          'random:minion:legion', 'random:minion:warband', 'random:minion:legion', 'random:minion:warband',
          'random:elite:legion',
          'random:minion:legion', 'random:minion:warband', 'random:minion:legion', 'random:minion:warband',
          'darius',
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.2,
        rewardExpMultiplier: 1.2,
        finalBossId: 'darius',
      },
    ],
  },
  {
    id: 'noxus_path_3',
    name: 'Shadow Blades',
    flavor: 'Survive the deadly Noxian assassins',
    paths: [
      {
        id: 'noxus_path_3_safe',
        name: 'Safe Route - Back Alleys',
        description: 'Navigate through dangerous streets',
        difficulty: 'safe' as const,
        enemyIds: [
          NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id,
          NOXUS_ELITES[0].id,
          NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id, NOXUS_MINIONS[2].id,
          NOXUS_BOSSES[2].id,
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
      },
      {
        id: 'noxus_path_3_balanced',
        name: 'Balanced Route - Assassin Guild',
        description: 'Infiltrate an assassin hideout',
        difficulty: 'safe' as const,
        enemyIds: [
          'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin',
          'random:elite:legion',
          'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin',
          'random:boss:assassin',
        ],
        lootType: 'mixed' as const,
        rewardGoldMultiplier: 1.0,
        rewardExpMultiplier: 1.0,
        finalBossId: 'noxus_master_assassin',
      },
      {
        id: 'noxus_path_3_risky',
        name: 'Risky Route - The Sinister Blade',
        description: 'Face Katarina, the deadliest assassin',
        difficulty: 'risky' as const,
        enemyIds: [
          'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin',
          'random:elite:legion',
          'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin', 'random:minion:assassin',
          'katarina',
        ],
        lootType: 'damage' as const,
        rewardGoldMultiplier: 1.2,
        rewardExpMultiplier: 1.2,
        finalBossId: 'katarina',
      },
    ],
  },
];
